const Items = [
    {
        id:1,
        name:'React',
        category:'Web',
        percent:'50%'
    },
    {
        id:2,
        name:'Next JS',
        category:'Web',
        percent:'10%'
    },
    {
        id:3,
        name:'Gatsby',
        category:'Web',
        percent:'15%'
    },
    {
        id:4,
        name:'Express Js',
        category:'Web',
        percent:"70%"
    },
    {
        id:5,
        name:'MySQL',
        category:'Web',
        percent:"30%"
    },
    {
        id:6,
        name:'Node Js',
        category:'Web',
        percent:"80%"
    },
    {
        id:7,
        name:'MongoDB',
        category:'Web',
        percent:'50%'
    },
    {
        id:8,
        name:'Javascript',
        category:'Programming',
        percent:'80%'
    },
    {
        id:9,
        name:'C++',
        category:'Programming',
        percent:'10%'
    },
    {
        id:10,
        name:'Python',
        category:'Programming',
        percent:'20%'
    },
    {
        id:11,
        name:'Java',
        category:'Programming',
        percent:'35%'
    },
    {
        id:12,
        name:'c',
        category:'Programming',
        percent:'30%'
    },
    {
        id:13,
        name:'Photoshop',
        category:'tools',
        percent:'50%'
    },
    {
        id:14,
        name:'Docker',
        category:'tools',
        percent:'25%'
    },
    {
        id:15,
        name:'Kubrnetes',
        category:'tools',
        percent:'20%'
    },
    {
        id:16,
        name:'Git',
        category:'tools',
        percent:'60%'
    },
    {
        id:17,
        name:'GraphQL',
        category:'others',
        percent:'10%'
    },
    {
        id:18,
        name:'SVG',
        category:'others',
        percent:'40%'
    },{
        id:19,
        name:'Redux',
        category:'others',
        percent:'40%'
    }
]

export default Items;